wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.12.17
    framework: sklearn
    is_jupyter_run: false
    is_kaggle_kernel: false
    python_version: 3.9.13
    start_time: 1658389455
    t:
      1:
      - 5
      - 53
      - 55
      2:
      - 5
      - 53
      - 55
      4: 3.9.13
      5: 0.12.17
      8:
      - 5
mlflow_model:
  desc: null
  value: random_forest_export:prod
test_dataset:
  desc: null
  value: domenico-vesia/nyc_airbnb/test_data.csv:latest
